// src/components/ShiftingFormModal.tsx
import { useState, useEffect } from "react";
import { useStore } from "../store/store";
import * as I from "./icons";

interface ModalProps {
    isOpen: boolean;
    onClose: () => void;
    preselectedStudentID?: string;
}

export default function ShiftingFormModal({ isOpen, onClose, preselectedStudentID }: ModalProps) {
    const { students, standings, activeTerm, activeUser, remarks, setRemarks, pushAudit } = useStore();
    const [localSelectedID, setLocalSelectedID] = useState<string>("");

    // FIXED: Segmented Control to swap between ATS and All Students
    const [filterMode, setFilterMode] = useState<'ats' | 'all'>('ats');
    const [searchQuery, setSearchQuery] = useState("");

    const [shiftingTo, setShiftingTo] = useState<string>("");
    const [printDate, setPrintDate] = useState<string>("");

    // FIXED: Dynamic Signature Inputs
    const [deptName, setDeptName] = useState<string>("IT/IS/CS/");
    const [chairName, setChairName] = useState<string>("");
    const [deanName, setDeanName] = useState<string>("Asst. Prof. Joy M. Dy");

    useEffect(() => {
        const timer = setTimeout(() => {
            const d = new Date();
            setPrintDate(`${(d.getMonth() + 1).toString().padStart(2, '0')}/${d.getDate()}/${d.getFullYear()}`);
        }, 0);
        return () => clearTimeout(timer);
    }, []);

    if (!isOpen) return null;

    const currentSelectedID = preselectedStudentID || localSelectedID;

    // Filter Logic
    const atsStandings = standings.filter(ts => ts.termID === activeTerm && ts.termAcademicStatus === 'Advised to Shift');
    const atsStudents = students.filter(s => atsStandings.some(ts => ts.studentID === s.studentID));

    const allSearchResults = students.filter(s => {
        if (!searchQuery) return false;
        const compositeString = `${s.studFirstName} ${s.studLastName} ${s.studLastName}, ${s.studFirstName} ${s.studentID}`.toLowerCase();
        return compositeString.includes(searchQuery.toLowerCase().trim());
    });

    const targetStudent = students.find(s => s.studentID === currentSelectedID);
    const targetStanding = standings.find(ts => ts.studentID === currentSelectedID && ts.termID === activeTerm);

    const romanYear = targetStudent?.yearLevel === 1 ? "I" : targetStudent?.yearLevel === 2 ? "II" : targetStudent?.yearLevel === 3 ? "III" : "IV";

    const handlePrint = () => {
        if (!activeUser) return alert("System Error: No active user session detected.");
        if (!targetStudent) return alert("Please select a valid student record to generate the form.");
        if (!shiftingTo.trim()) return alert("Please specify the destination program the student is shifting to.");

        const isATS = targetStanding?.termAcademicStatus === 'Advised to Shift';
        const newRemark = {
            remarkID: `REM-${Date.now()}`,
            content: `Official Shifting Form document automatically generated by ${activeUser.userFirstName} ${activeUser.userLastName}. Destination: ${shiftingTo.toUpperCase()} (${isATS ? 'Mandatory' : 'Voluntary'})`,
            timestamp: new Date().toISOString(),
            userID: activeUser.userID,
            standingID: targetStanding ? targetStanding.standingID : `TEMP-${targetStudent.studentID}`,
            category: "Shifting Recommended"
        };

        setRemarks([...remarks, newRemark]);
        pushAudit("GENERATED_SHIFTING_FORM", targetStudent.studentID);

        window.print();
        onClose();
    };

    return (
        <>
            <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 dark:bg-black/60 backdrop-blur-sm print:hidden p-4">
                <div className="w-full max-w-2xl overflow-hidden rounded-2xl bg-white dark:bg-slate-800 shadow-2xl transition-colors flex flex-col max-h-[90vh]">
                    <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/50 px-6 py-4 shrink-0">
                        <h2 className="font-bold text-slate-800 dark:text-slate-100">Generate Shifting Form</h2>
                        <button onClick={onClose} className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-300"><I.X className="h-5 w-5" /></button>
                    </div>

                    <div className="p-6 overflow-y-auto flex-1">
                        {!preselectedStudentID && (
                            <div className="mb-5 flex rounded-lg bg-slate-100 dark:bg-slate-900 p-1">
                                <button onClick={() => { setFilterMode('ats'); setLocalSelectedID(""); }} className={`flex-1 rounded-md py-1.5 text-xs font-bold transition ${filterMode === 'ats' ? 'bg-white dark:bg-slate-800 text-blue-700 dark:text-blue-400 shadow-sm' : 'text-slate-500 dark:text-slate-400'}`}>Flagged (ATS)</button>
                                <button onClick={() => { setFilterMode('all'); setLocalSelectedID(""); }} className={`flex-1 rounded-md py-1.5 text-xs font-bold transition ${filterMode === 'all' ? 'bg-white dark:bg-slate-800 text-blue-700 dark:text-blue-400 shadow-sm' : 'text-slate-500 dark:text-slate-400'}`}>Search All (Voluntary)</button>
                            </div>
                        )}

                        <label className="mb-2 block text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">Select Student</label>

                        {!preselectedStudentID && filterMode === 'all' ? (
                            <div className="mb-5 relative">
                                <I.Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
                                <input type="text" placeholder="Search by ID or Name..." value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} className="w-full rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 py-2.5 pl-10 pr-4 text-sm outline-none transition focus:border-blue-700" />
                                {searchQuery && (
                                    <div className="absolute top-full mt-1 w-full max-h-48 overflow-y-auto rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 shadow-lg z-10">
                                        {allSearchResults.map(s => (
                                            <button key={s.studentID} onClick={() => { setLocalSelectedID(s.studentID); setSearchQuery(""); }} className="flex w-full flex-col items-start border-b border-slate-50 dark:border-slate-700/50 px-4 py-2 text-left hover:bg-slate-50 dark:hover:bg-slate-700">
                                                <span className="font-semibold text-slate-800 dark:text-slate-200 text-sm">{s.studLastName}, {s.studFirstName}</span>
                                                <span className="font-mono text-xs text-slate-500">{s.studentID}</span>
                                            </button>
                                        ))}
                                    </div>
                                )}
                            </div>
                        ) : (
                            <select
                                value={currentSelectedID}
                                onChange={(e) => setLocalSelectedID(e.target.value)}
                                disabled={!!preselectedStudentID}
                                className="mb-5 w-full rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 p-3 text-sm font-semibold text-slate-800 dark:text-slate-200 outline-none focus:border-blue-700 disabled:opacity-70 transition-colors"
                            >
                                <option value="" disabled>-- Select a student --</option>
                                {preselectedStudentID && targetStudent ? (
                                    <option value={targetStudent.studentID}>{targetStudent.studLastName}, {targetStudent.studFirstName} ({targetStudent.studentID})</option>
                                ) : atsStudents.map(s => (
                                    <option key={s.studentID} value={s.studentID}>{s.studLastName}, {s.studFirstName} ({s.studentID})</option>
                                ))}
                            </select>
                        )}

                        {targetStudent && (
                            <div className="mb-5 flex items-center justify-between rounded-lg border border-blue-100 dark:border-blue-900 bg-blue-50 dark:bg-blue-900/20 p-3">
                                <div>
                                    <div className="font-bold text-blue-800 dark:text-blue-300">{targetStudent.studLastName}, {targetStudent.studFirstName}</div>
                                    <div className="text-xs text-blue-600 dark:text-blue-400">{targetStudent.programCode} • {targetStudent.studentID}</div>
                                </div>
                                <span className={`rounded px-2 py-1 text-[10px] font-bold uppercase ${targetStanding?.termAcademicStatus === 'Advised to Shift' ? 'bg-coral text-white' : 'bg-slate-200 text-slate-700'}`}>
                                    {targetStanding?.termAcademicStatus === 'Advised to Shift' ? 'Advised to Shift' : 'Voluntary'}
                                </span>
                            </div>
                        )}

                        <label className="mb-2 block text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">Destination Program</label>
                        <input
                            required placeholder="e.g., BS MATH" value={shiftingTo} onChange={e => setShiftingTo(e.target.value.toUpperCase())}
                            className="mb-5 w-full rounded-lg border border-slate-300 dark:border-slate-600 bg-transparent dark:bg-slate-900 p-3 text-sm outline-none focus:border-blue-700 uppercase"
                        />

                        <div className="grid grid-cols-2 gap-4 border-t border-slate-100 dark:border-slate-700 pt-5">
                            <div className="col-span-2"><label className="block text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">Signatories Configuration</label></div>
                            <div>
                                <label className="mb-1 block text-[10px] font-semibold text-slate-400">Department</label>
                                <input value={deptName} onChange={e => setDeptName(e.target.value)} className="w-full rounded border border-slate-300 dark:border-slate-600 bg-transparent p-2 text-sm outline-none focus:border-blue-700" />
                            </div>
                            <div>
                                <label className="mb-1 block text-[10px] font-semibold text-slate-400">Chairperson</label>
                                <input placeholder="Name (Optional)" value={chairName} onChange={e => setChairName(e.target.value)} className="w-full rounded border border-slate-300 dark:border-slate-600 bg-transparent p-2 text-sm outline-none focus:border-blue-700" />
                            </div>
                            <div className="col-span-2">
                                <label className="mb-1 block text-[10px] font-semibold text-slate-400">Dean</label>
                                <input value={deanName} onChange={e => setDeanName(e.target.value)} className="w-full rounded border border-slate-300 dark:border-slate-600 bg-transparent p-2 text-sm outline-none focus:border-blue-700" />
                            </div>
                        </div>

                    </div>

                    <div className="flex shrink-0 justify-end gap-3 border-t border-slate-100 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/50 p-4">
                        <button onClick={onClose} className="rounded-lg px-4 py-2 text-sm font-semibold text-slate-500 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700 transition">Cancel</button>
                        <button onClick={handlePrint} disabled={!targetStudent || !shiftingTo.trim()} className="flex items-center gap-2 rounded-lg bg-blue-700 dark:bg-blue-600 px-5 py-2 text-sm font-bold text-white shadow-sm hover:bg-blue-800 disabled:opacity-50 transition">
                            <I.Printer className="h-4 w-4" /> Print Document
                        </button>
                    </div>
                </div>
            </div>

            {targetStudent && (
                <div className="hidden print:block print:fixed print:inset-0 print:z-[9999] print:bg-white print:text-black">
                    <style type="text/css">{`@media print { @page { size: portrait; margin: 1in; } body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }`}</style>
                    <div className="mx-auto max-w-[8in] font-serif text-[15px]">

                        <div className="mb-10 flex items-center gap-6">
                            <img src="/imgSilliman.png" alt="Silliman Logo" className="h-24 w-24 object-contain shrink-0" />
                            <div className="border-l-2 border-dashed border-black pl-6 flex-1">
                                <h2 className="text-xl tracking-[0.15em] text-black">COLLEGE OF COMPUTER STUDIES</h2>
                                {/* FIXED: Shrunk from text-4xl to text-[28px] and tightened tracking to fit perfectly on one line */}
                                <h1 className="text-[28px] font-serif tracking-widest mt-1 mb-1 text-black font-bold">SILLIMAN UNIVERSITY</h1>
                                <p className="text-[15px] italic font-serif text-black">Building Competence, Character & Faith</p>
                            </div>
                        </div>

                        <div className="mb-8 text-center"><h3 className="font-bold italic uppercase underline tracking-wider text-lg">SHIFTING FORM</h3></div>
                        <div className="mb-6"><p className="uppercase font-bold">TO WHOM IT MAY CONCERN:</p></div>
                        <div className="ml-12 mb-6 text-justify leading-relaxed"><p className="font-bold">This is to certify that the subjects and/or grades listed below are true and correct:</p></div>

                        <div className="ml-24 mb-10 text-[15px] font-bold">
                            <div className="grid grid-cols-[180px_1fr] gap-4 mb-1"><span className="uppercase">NAME</span><span className="uppercase">: <span className="underline underline-offset-4">{targetStudent.studLastName}, {targetStudent.studFirstName}</span></span></div>
                            <div className="grid grid-cols-[180px_1fr] gap-4 mb-1"><span className="uppercase">COURSE & YEAR</span><span className="uppercase">: <span className="underline underline-offset-4">{targetStudent.programCode.replace(/[0-9]/g, '').replace('BS', 'BS ')} - {romanYear}</span></span></div>
                            <div className="grid grid-cols-[180px_1fr] gap-4 mt-4"><span className="uppercase">SHIFTING TO</span><span className="uppercase">: <span className="underline underline-offset-4">{shiftingTo}</span></span></div>
                        </div>

                        <div className="mb-4">
                            <p className="uppercase font-bold mb-4">NOTE:</p>
                            <div className="ml-12 font-bold space-y-1">
                                <p>1.) Kindly see attached separate student grade form.</p>
                                <p>2.) {targetStanding?.termAcademicStatus === 'Advised to Shift' ? 'Advised to shift' : 'Voluntary shifting'}</p>
                            </div>
                        </div>

                        <div className="my-8 text-left text-[15px] tracking-widest font-mono font-bold overflow-hidden whitespace-nowrap">
                            +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                        </div>

                        <div className="grid grid-cols-2 gap-8 mt-6 text-[15px]">
                            <div>
                                <div className="mb-4">Prepared by:</div>
                                <div className="ml-10 w-[280px]">
                                    <div className="w-full inline-block border-b border-black font-bold uppercase text-center px-4 mb-2">
                                        {activeUser?.userType === 'Deans_Office_Staff' ? `${activeUser.userFirstName} ${activeUser.userLastName}` : "ANGELA C. LIGUARDA"}
                                    </div>
                                    <div className="grid grid-cols-[70px_1fr] gap-x-2 gap-y-1 items-end mt-2">
                                        <span>Date</span><span className="flex items-center gap-1">: <span className="border-b border-black flex-1 inline-block h-5 px-1">{printDate}</span></span>
                                        <span>Remarks</span><span className="flex items-center gap-1">: <span className="border-b border-black flex-1 inline-block h-5"></span></span>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <div className="mb-4">Noted by:</div>
                                <div className="ml-10 flex flex-col gap-10">
                                    <div className="w-[240px]">
                                        {/* FIXED: Dynamic string-length sizing logic prevents the Chairperson name from expanding the fixed border */}
                                        <div className={`border-b border-black font-bold text-center h-5 mb-0.5 whitespace-nowrap overflow-hidden text-ellipsis ${chairName.length > 22 ? 'text-[11px] pt-1' : 'text-[15px]'}`}>
                                            {chairName.toUpperCase()}
                                        </div>
                                        <div className="text-center">{deptName} Chairperson</div>
                                    </div>
                                    <div className="w-[240px]">
                                        <div className="border-b border-black font-bold text-center h-5 mb-0.5 whitespace-nowrap overflow-hidden text-ellipsis">{deanName}</div>
                                        <div className="text-center">Dean</div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            )}s
        </>
    );
}