// src/components/ShiftingFormModal.tsx
import { useState, useEffect } from "react";
import { useStore } from "../store/store";
import * as I from "./icons";

interface ModalProps {
    isOpen: boolean;
    onClose: () => void;
    preselectedStudentID?: string;
}

export default function ShiftingFormModal({ isOpen, onClose, preselectedStudentID }: ModalProps) {
    const { students, standings, activeTerm, activeUser, remarks, setRemarks, pushAudit } = useStore();
    const [localSelectedID, setLocalSelectedID] = useState<string>("");

    const [shiftingTo, setShiftingTo] = useState<string>("");
    const [printDate, setPrintDate] = useState<string>("");

    useEffect(() => {
        const timer = setTimeout(() => {
            // Formats to match the DOCX layout (e.g., 06/9/2026)
            const d = new Date();
            setPrintDate(`${(d.getMonth() + 1).toString().padStart(2, '0')}/${d.getDate()}/${d.getFullYear()}`);
        }, 0);
        return () => clearTimeout(timer);
    }, []);

    if (!isOpen) return null;

    const currentSelectedID = preselectedStudentID || localSelectedID;

    const atsStandings = standings.filter(ts => ts.termID === activeTerm && ts.termAcademicStatus === 'Advised to Shift');
    const atsStudents = students.filter(s => atsStandings.some(ts => ts.studentID === s.studentID));

    const targetStudent = students.find(s => s.studentID === currentSelectedID);
    const targetStanding = atsStandings.find(ts => ts.studentID === currentSelectedID);

    const romanYear = targetStudent?.yearLevel === 1 ? "I" : targetStudent?.yearLevel === 2 ? "II" : targetStudent?.yearLevel === 3 ? "III" : "IV";

    const handlePrint = () => {
        if (!activeUser) return alert("System Error: No active user session detected.");
        if (!targetStudent || !targetStanding) return alert("Please select a valid student record to generate the form.");
        if (!shiftingTo.trim()) return alert("Please specify the destination program the student is shifting to.");

        const newRemark = {
            remarkID: `REM-${Date.now()}`,
            content: `Official Shifting Form document automatically generated by ${activeUser.userFirstName} ${activeUser.userLastName}. Destination: ${shiftingTo.toUpperCase()}`,
            timestamp: new Date().toISOString(),
            userID: activeUser.userID,
            standingID: targetStanding.standingID,
            category: "Shifting Recommended"
        };

        setRemarks([...remarks, newRemark]);
        pushAudit("GENERATED_SHIFTING_FORM", targetStudent.studentID);

        window.print();
        onClose();
    };

    return (
        <>
            {/* Modal UI */}
            <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 dark:bg-black/60 backdrop-blur-sm print:hidden">
                <div className="w-full max-w-lg overflow-hidden rounded-2xl bg-white dark:bg-slate-800 shadow-2xl transition-colors">
                    <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/50 px-6 py-4">
                        <h2 className="font-bold text-slate-800 dark:text-slate-100">Generate Shifting Form</h2>
                        <button onClick={onClose} className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-300"><I.X className="h-5 w-5" /></button>
                    </div>

                    <div className="p-6">
                        <label className="mb-2 block text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">Select Flagged Student</label>
                        <select
                            value={currentSelectedID}
                            onChange={(e) => setLocalSelectedID(e.target.value)}
                            disabled={!!preselectedStudentID}
                            className="mb-5 w-full rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 p-3 text-sm font-semibold text-slate-800 dark:text-slate-200 outline-none focus:border-blue-700 dark:focus:border-blue-500 disabled:bg-slate-100 dark:disabled:bg-slate-800 disabled:opacity-70 transition-colors"
                        >
                            <option value="" disabled>-- Select a student --</option>
                            {atsStudents.map(s => (
                                <option key={s.studentID} value={s.studentID}>{s.studLastName}, {s.studFirstName} ({s.studentID})</option>
                            ))}
                        </select>

                        {!preselectedStudentID && atsStudents.length === 0 && (
                            <p className="mb-5 text-xs font-semibold text-amber-600 dark:text-amber-500">No students are currently flagged as Advised to Shift in this term.</p>
                        )}

                        <label className="mb-2 block text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">Destination Program</label>
                        <input
                            required
                            placeholder="e.g., BS MATH"
                            value={shiftingTo}
                            onChange={e => setShiftingTo(e.target.value.toUpperCase())}
                            className="w-full rounded-lg border border-slate-300 dark:border-slate-600 bg-transparent dark:bg-slate-900 p-3 text-sm outline-none focus:border-blue-700 dark:focus:border-blue-500 transition-colors uppercase"
                        />

                        <div className="mt-6 flex justify-end gap-3 border-t border-slate-100 dark:border-slate-700 pt-4">
                            <button onClick={onClose} className="rounded-lg px-4 py-2 text-sm font-semibold text-slate-500 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-700 transition">Cancel</button>
                            <button onClick={handlePrint} disabled={!targetStudent || !shiftingTo.trim()} className="flex items-center gap-2 rounded-lg bg-blue-700 dark:bg-blue-600 px-5 py-2 text-sm font-bold text-white shadow-sm hover:bg-blue-800 dark:hover:bg-blue-500 disabled:opacity-50 transition">
                                <I.Printer className="h-4 w-4" /> Print Document
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            {/* PRINT LAYOUT: Strictly replicates the Official DOCX Format */}
            {targetStudent && (
                <div className="hidden print:block print:fixed print:inset-0 print:z-[9999] print:bg-white print:text-black">
                    {/* Forces Portrait Mode and exact 1-inch margins */}
                    <style type="text/css">
                        {`
                            @media print {
                                @page { size: portrait; margin: 1in; }
                                body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
                            }
                        `}
                    </style>

                    <div className="mx-auto max-w-[8in] font-serif text-[15px]">

                        {/* Header: Left Logo & Dashed Border */}
                        <div className="mb-10 flex items-center gap-6">
                            <img src="/imgSilliman.png" alt="Silliman Logo" className="h-28 w-28 object-contain shrink-0" />
                            <div className="border-l-2 border-dashed border-black pl-6 flex-1">
                                <h2 className="text-xl tracking-[0.15em] text-black">COLLEGE OF COMPUTER STUDIES</h2>
                                <h1 className="text-4xl font-serif tracking-[0.2em] mt-1 mb-1 text-black">SILLIMAN UNIVERSITY</h1>
                                <p className="text-[15px] italic font-serif text-black">Building Competence, Character & Faith</p>
                            </div>
                        </div>

                        {/* Title (Italic, Underlined, Bold) */}
                        <div className="mb-8 text-center">
                            <h3 className="font-bold italic uppercase underline tracking-wider text-lg">SHIFTING FORM</h3>
                        </div>

                        <div className="mb-6">
                            <p className="uppercase font-bold">TO WHOM IT MAY CONCERN:</p>
                        </div>

                        <div className="ml-12 mb-6 text-justify leading-relaxed">
                            <p className="font-bold">This is to certify that the subjects and/or grades listed below are true and correct:</p>
                        </div>

                        {/* Student Details Grid (Bold with Underlined Values) */}
                        <div className="ml-24 mb-10 text-[15px] font-bold">
                            <div className="grid grid-cols-[180px_1fr] gap-4 mb-1">
                                <span className="uppercase">NAME</span>
                                <span className="uppercase">: <span className="underline underline-offset-4">{targetStudent.studLastName}, {targetStudent.studFirstName}</span></span>
                            </div>
                            <div className="grid grid-cols-[180px_1fr] gap-4 mb-1">
                                <span className="uppercase">COURSE & YEAR</span>
                                <span className="uppercase">: <span className="underline underline-offset-4">{targetStudent.programCode.replace(/[0-9]/g, '').replace('BS', 'BS ')} - {romanYear}</span></span>
                            </div>
                            <div className="grid grid-cols-[180px_1fr] gap-4 mt-4">
                                <span className="uppercase">SHIFTING TO</span>
                                <span className="uppercase">: <span className="underline underline-offset-4">{shiftingTo}</span></span>
                            </div>
                        </div>

                        {/* Note Section (Numbered List) */}
                        <div className="mb-4">
                            <p className="uppercase font-bold mb-4">NOTE:</p>
                            <div className="ml-12 font-bold space-y-1">
                                <p>1.) Kindly see attached separate student grade form.</p>
                                <p>2.) Advised to shift</p>
                            </div>
                        </div>

                        {/* Divider */}
                        <div className="my-8 text-left text-[15px] tracking-widest font-mono font-bold overflow-hidden whitespace-nowrap">
                            +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                        </div>

                        {/* Exact Signature Grid Recreation */}
                        <div className="grid grid-cols-2 gap-8 mt-6 text-[15px]">

                            {/* Left Column (Prepared By) */}
                            <div>
                                <div className="mb-4">Prepared by:</div>
                                {/* Fixed width container aligns name underline strictly to the Date/Remarks boundaries */}
                                <div className="ml-10 w-[280px]">
                                    <div className="w-full inline-block border-b border-black font-bold uppercase text-center px-4 mb-2">
                                        {activeUser?.userType === 'Deans_Office_Staff' ? `${activeUser.userFirstName} ${activeUser.userLastName}` : "ANGELA C. LIGUARDA"}
                                    </div>
                                    <div className="grid grid-cols-[70px_1fr] gap-x-2 gap-y-1 items-end mt-2">
                                        <span>Date</span>
                                        <span className="flex items-center gap-1">: <span className="border-b border-black flex-1 inline-block h-5 px-1">{printDate}</span></span>
                                        <span>Remarks</span>
                                        <span className="flex items-center gap-1">: <span className="border-b border-black flex-1 inline-block h-5"></span></span>
                                    </div>
                                </div>
                            </div>

                            {/* Right Column (Noted By) */}
                            <div>
                                <div className="mb-4">Noted by:</div>
                                <div className="ml-10 flex flex-col gap-10">
                                    <div className="w-[240px]">
                                        <div className="border-b border-black h-5 mb-0.5"></div>
                                        <div className="text-center">IT/IS/CS/ Chairperson</div>
                                    </div>
                                    <div className="w-[240px]">
                                        <div className="border-b border-black font-bold text-center h-5 mb-0.5">
                                            Asst. Prof. Joy M. Dy
                                        </div>
                                        <div className="text-center">Dean</div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            )}
        </>
    );
}